spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  kafka:
    bootstrap-servers: localhost:9092  # Kafka 서버 주소
    consumer:
      group-id: unique-chat-group-${random.uuid}  # 개별 사용자 단위로 설정하기 위해 유니크한 그룹 ID를 할당
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9093


jwt:
  secret:
    key: ${JWT_SECRET_KEY}

web-socket:
  secret:
    key: ${WEB_SOCKET_SECRET_KEY}

s3:
  credentials:
    access-key: ${S3_CREDENTIALS_ACCESS_KEY}
    secret-key: ${S3_CREDENTIALS_SECRET_KEY}
    region: ${S3_CREDENTIALS_REGION}
  bucket: ${S3_BUCKET}
