name: Deploy Docker App to EC2

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH for EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "EC2_USER=${EC2_USER}"
          echo "EC2_HOST=${EC2_HOST}"
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 400 private_key.pem

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t kangiwon/my-app:latest .

      - name: Push the Docker image
        run: docker push kangiwon/my-app:latest

      - name: Load Docker image and run container on EC2
        run: |
          ssh -i ${{SSH_PRIVATE_KEY}} ec2-user@43.202.17.26
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker run -d --name my-app --env-file ~/project/.env -p 80:80 my-app:latest
          EOF
